### ISSUE TITLE
Possible bug in precision calculation

### ISSUE THREAD

**Issue by ivendrov** [s-gupta/visual-concepts#1]
I'm trying to figure out what [this stretch of code](https://github.com/s-gupta/visual-concepts/blob/master/cap_eval_utils.py#L26-L34) does. 

It seems to be computing precision, but in a lopsided way: it counts true positives multiple times (number of captions where the word occurs \* 0.8), but false positives at most once (1 if the word occurs in no captions, 0.2 if it occurs in no captions). Is this the intended behaviour?

**Comment by s-gupta** [comment]
This is the intended behavior. Please look at Section 4.2 of http://arxiv.org/pdf/1504.00325v2.pdf on how these calculations are performed. There are 2 things going on here: 

a) images which have a particular word in multiple captions are more important to get right, and
b) computed metric should be comparable to the human agreement reported in the CVRP15 paper.

**Comment by ivendrov** [comment]
Ah, that makes sense - I had only consulted the CVPR15 paper. Thank you for clarifying!
