### ISSUE TITLE
visualize the spatial response map

### ISSUE THREAD

**Issue by zhuolinumd** [s-gupta/visual-concepts#10]
@s-gupta hi Saurabh, can you provide me some hints about how to visualize the spatial response maps p^w_{i,j} for word w? The fc8 layer corresponds to 12x12=144 regions (of size 224x224), why the visualized maps such as figure 2, are not in rectangle shape? did you combine these 12x12 regions? Thank you!

**Comment by hpts23** [comment]
@s-gupta 
  I am also interested in how to generate the heat maps!
@jiang2764 
  Do you already solve it?

**Comment by zhuolinumd** [comment]
Just simply resize the feature map to the size of input image
