### ISSUE TITLE
Can not download pretrained model

### ISSUE THREAD

**Issue by camel007** [s-gupta/visual-concepts#14]
I can not download the models or pretrain data from ftp://ftp.cs.berkeley.edu/pub/projects/vision/im2cap-cvpr15b/* .

**Comment by s-gupta** [comment]
I think the server is down at the moment. I will wait till tomorrow if this comes back up, otherwise copy the data to another location and post a link here. Sorry for the delay and the inconvenience.

**Comment by camel007** [comment]
Thanks a lot!

**Comment by s-gupta** [comment]
The server seems to be online again, so you can download the data from there. Alternatively I copied the data [here](https://www.dropbox.com/sh/e0r7tbnl53wtn66/AABDLB-bxTLsq-JpzmHzxgUsa?dl=0). Sorry for the inconvenience.
