### ISSUE TITLE
Getting nicer image descriptions?

### ISSUE THREAD

**Issue by n3011** [s-gupta/visual-concepts#3]
Hi @s-gupta , I was trying to do some experiment with your tool, t is really impressive.

But the problems is tha while running the demo, I am unable to get a proper sentence. 

a [1.00, 1.00]  
the [0.94, 0.94]  
on [0.91, 0.91]  
bus [0.89, 0.89]  
street [0.88, 0.88]  
in [0.87, 0.87]  
of [0.86, 0.86]  
man [0.84, 0.84]  
truck [0.81, 0.81]  
parking [0.81, 0.81]  
car [0.81, 0.81]  
parked [0.80, 0.80]  
and [0.79, 0.79]  
with [0.76, 0.76]  
woman [0.76, 0.76]  
standing [0.71, 0.71]  
is [0.70, 0.70]  
blue [0.68, 0.68]  
motorcycle [0.65, 0.65]  
people [0.62, 0.62]  
tennis [0.61, 0.61]  
black [0.58, 0.58]  
cars [0.58, 0.58]  
city [0.57, 0.57]  
to [0.57, 0.57]  
walking [0.55, 0.55]  
bed [0.53, 0.53]  
luggage [0.53, 0.53]  
two [0.52, 0.52]  
down [0.52, 0.52]  
 there are lots of unnecessary words, How can i remove those?

**Comment by chapternewscu** [comment]
u can see this demo just for MIL, it's not complete.
