### ISSUE TITLE
Cannot load Caffe model in file demo.ipynb

### ISSUE THREAD

**Issue by PC91** [s-gupta/visual-concepts#6]
Hi,

I tried to run the file demo.ipynb and when loading Caffe model, I had the following error:

[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 161:12: Message type "caffe.LayerParameter" has no field named "mil_param".
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0107 22:52:49.491786 7653 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: home/chau/Dropbox/img_vid_cap/Code/cnn_model/vgg_finetuned/mil_finetune.prototxt.deploy
*** Check failure stack trace: ***
Aborted (core dumped)

The system said that it couldn't find the "mil_param" type. Do I have to install additional dependency or reuse code from other papers?
(My system is Ubuntu 14.04, CPU-only mode)

Thank you very much!

**Comment by s-gupta** [comment]
Did you follow instructions to setup caffe (step 2, here
<https://github.com/s-gupta/visual-concepts#installation-instructions>)?
mil_param should be defined in mil branch of git@github.com:
s-gupta/caffe.git

Thanks,
Saurabh

**Comment by PC91** [comment]
Thanks! It worked finally. My error is that I installed Caffe library first and I only cloned this repository without using Github terminal.
