### ISSUE TITLE
unable to make branch mil

### ISSUE THREAD

**Issue by RubickH** [s-gupta/visual-concepts#7]
Hi
I followed your instruction to install the caffe in mil branch. 

`git clone git@github.com:s-gupta/caffe.git code/caffe 
cd code/caffe 
git checkout mil` 

After entering the codes above, when I was trying to make the caffe, I got this:

`Makefile:6: *** Makefile.config not found. See Makefile.config.example..  Stop.`

So I copied the Makefile.config.example and change the hdf5 path (my system is ubuntu 16.04) in the Makefile.config.
I also uncommented  #USE_CUDNN (I've already installed cuda 8.0 ) and  # WITH_ PYTHON_LAYER .
Then, I tried to do ' make -j 16', and I got many errors like this

`Makefile:516: recipe for target '.build_release/src/caffe/layers/data_layer.o' failed
make: *** [.build_release/src/caffe/layers/data_layer.o] Error 1`

I installed caffe before and the changes in Makefile.config worked, I have no idea why I could not install the caffe in mil branch.

Thank you very much!

**Comment by CherishineNi** [comment]
I have met the same problem. Could you tell me how to solve this problem? @RubickH
