### ISSUE TITLE
"caffe.LayerParameter" has no field named "mil_data_param"

### ISSUE THREAD

**Issue by rjing2525** [s-gupta/visual-concepts#8]
In the training process, I encountered with this error message: "caffe.LayerParameter" has no field named "mil_data_param". Anyone has an idea how to deal with it?

**Comment by s-gupta** [comment]
Hi,

Did you try installing and using the caffe version specified in the [Installation Instructions](https://github.com/s-gupta/visual-concepts#installation-instructions). The caffe specified there has the appropriate layer that you need.

Thanks,
Saurabh

**Comment by rjing2525** [comment]
Thank you!

**Comment by CherishineNi** [comment]
> Thank you!

which caffe is used for this project? Is it from https://github.com/BVLC/caffe?
